/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MateriaIdRouteImport } from './routes/materia.$id'
import { Route as EpisodioIdRouteImport } from './routes/episodio.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MateriaIdRoute = MateriaIdRouteImport.update({
  id: '/materia/$id',
  path: '/materia/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EpisodioIdRoute = EpisodioIdRouteImport.update({
  id: '/episodio/$id',
  path: '/episodio/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/episodio/$id': typeof EpisodioIdRoute
  '/materia/$id': typeof MateriaIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/episodio/$id': typeof EpisodioIdRoute
  '/materia/$id': typeof MateriaIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/episodio/$id': typeof EpisodioIdRoute
  '/materia/$id': typeof MateriaIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/episodio/$id' | '/materia/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/episodio/$id' | '/materia/$id'
  id: '__root__' | '/' | '/episodio/$id' | '/materia/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EpisodioIdRoute: typeof EpisodioIdRoute
  MateriaIdRoute: typeof MateriaIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/materia/$id': {
      id: '/materia/$id'
      path: '/materia/$id'
      fullPath: '/materia/$id'
      preLoaderRoute: typeof MateriaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/episodio/$id': {
      id: '/episodio/$id'
      path: '/episodio/$id'
      fullPath: '/episodio/$id'
      preLoaderRoute: typeof EpisodioIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EpisodioIdRoute: EpisodioIdRoute,
  MateriaIdRoute: MateriaIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
